# Generated by Django 5.1.5 on 2025-01-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farmacia.pedido')),
            ],
        ),
    ]
