# Generated by Django 5.1.5 on 2025-01-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0005_venta_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='nombre_producto',
            field=models.CharField(max_length=100),
        ),
    ]
