# Generated by Django 5.1.5 on 2025-01-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0006_alter_venta_nombre_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
