# Generated by Django 5.1.5 on 2025-01-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0007_remove_venta_pedido_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='medicamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Farmacia.medicamento'),
            preserve_default=False,
        ),
    ]
