# Generated by Django 5.1.5 on 2025-01-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0008_remove_venta_nombre_producto_venta_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='iva',
        ),
    ]
