# Generated by Django 5.1.5 on 2025-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0010_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ci',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
