# Generated by Django 5.1.5 on 2025-01-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0011_cliente_ci_alter_medicamento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmacia.sucursal'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(default='(L)', max_length=100),
        ),
    ]
