# Generated by Django 5.1.5 on 2025-01-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0012_venta_entrega_alter_medicamento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='entrega',
        ),
    ]
