# Generated by Django 5.1.5 on 2025-01-26 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0014_venta_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='entrega',
        ),
    ]
