# Generated by Django 5.1.5 on 2025-01-26 22:58

import Farmacia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0015_remove_venta_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='entrega',
            field=models.FloatField(blank=True, null=True, verbose_name=Farmacia.models.Sucursal),
        ),
    ]
