# Generated by Django 5.1.5 on 2025-01-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0019_administradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='correo',
            field=models.CharField(max_length=30),
        ),
    ]
