# Generated by Django 5.1.5 on 2025-01-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0020_alter_administradores_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administradores',
            new_name='Administrador',
        ),
    ]
