# Generated by Django 5.1.5 on 2025-01-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0021_rename_administradores_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
