# Generated by Django 5.1.5 on 2025-01-31 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0022_delete_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='Farmacia.sucursal'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='Farmacia.sucursal'),
        ),
    ]
