# Generated by Django 5.1.5 on 2025-01-31 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0023_alter_transferencia_sucursal_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='Farmacia.sucursal'),
        ),
    ]
