# Generated by Django 5.1.5 on 2025-02-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0024_alter_medicamento_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
